[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "cargo", "rust-std", "llvm-tools"]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin"
]
profile = "minimal"
