[package]
name = "rowscript"
version = "1.0.0-alpha.5"
edition = "2021"

[dependencies.rowscript-core]
path = "../core"

[dependencies.clap]
version = "4.5.20"
features = ["derive"]

[dependencies]
log = "0.4.22"
env_logger = "0.11.5"
