[package]
name = "rowscript"
version = "1.0.0-alpha.5"
edition = "2024"

[dependencies.rowscript-core]
path = "../core"

[dependencies.clap]
version = "4.5.31"
features = ["derive"]

[dependencies]
log = "0.4.26"
env_logger = "0.11.6"
