name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Rustup
        run: |
          rustup toolchain install stable --component rustfmt clippy --profile minimal --force
      - name: Run rustfmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all
      # FIXME: All tests are based on filesystem for now, Miri is not usable here.
      #- name: Test with Miri
      #  run: cargo miri test --release
      - name: Build
        run: cargo build --release --verbose
      - name: Run tests
        run: cargo test --verbose
